# Generated by Django 4.0.6 on 2022-08-03 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(default=None)),
                ('to_publish', models.BooleanField(default=False)),
                ('was_published', models.BooleanField(default=False)),
                ('post_url', models.TextField(default=None)),
            ],
        ),
    ]
