# Generated by Django 4.0.6 on 2022-08-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_url',
            field=models.TextField(null=True),
        ),
    ]
