# Generated by Django 4.0.6 on 2022-08-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_post_url_alter_post_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='task_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
